export const translations = {
    vi: {
        home: 'Trang chủ',
        aboutUs: 'Về chúng tôi',
        product: 'Sản phẩm',
        contact: 'Liên hệ',
        certificate: ' Chứng chỉ',
        CONTACT_US: 'LIÊN HỆ VỚI CHÚNG TÔI',
        HABIMECT_NAME: 'CÔNG TY CỔ PHẦN TẬP ĐOÀN HABIMEC',
        event: 'Sự kiện',
        More: "Thêm",
        MESSAGE: "THÔNG ĐIỆP",
        MESSAGE_DESCRIPTION_1: 'Là Tập đoàn sản xuất hàng đầu trong lĩnh vực thiết bị y tế với nhiều kinh nghiệm trong sản xuất, thương mại xuất khẩu sang châu Âu và Mỹ. Sự bùng phát của Coronavirus mới đã gây ra một cuộc khủng hoảng sức khỏe toàn cầu nghiêm trọng. Cùng bảo vệ sức khỏe cộng đồng và ngăn ngừa sự lây lan của bệnh Covid-19. Chúng tôi xin giới thiệu các sản phẩm chủ yếu bao gồm: Khẩu trang, quần áo chống dịch & găng tay và các thiết bị bảo vệ khác có thể giúp ngăn chặn sự lây lan của coronavirus.....',
        MESSAGE_DESCRIPTION_2: 'Là thương hiệu Việt Nam, chúng tôi sở hữu hệ thống nhà máy hoạt động đúng theo tiêu chuẩn ISO 9001:2015 và ISO 13485:2016.',
        MESSAGE_DESCRIPTION_3: 'Các sản phẩm y tế của chúng tôi được cam kết đảm bảo về chất lượng và mẫu mã bởi FDA và CE.',
        MESSAGE_DESCRIPTION_4: 'HABIMEC GROUP không ngừng nghiên cứu, hợp tác và phát triển các sản phẩm y tế tốt nhất, giúp nâng cao hiệu suất chăm sóc sức khỏe cộng đồng',
        nitrile_title: 'GĂNG TAY Y TẾ NITRILE',
        nitrile_description: 'Được làm từ cao su nhân tạo Nitrile. Găng tay Nitrile là sản phẩm tuyệt vời dành cho những người bị dị ứng với cao su tự nhiên....',
        latex_title: 'GĂNG TAY Y TẾ LATEX GLOVES',
        latex_description: 'Găng tay latex là loại găng tay được chiết xuất 100% từ cao su tự nhiên....',
        content: 'Thông tin',
        specifications: 'Thành phần',
        location: 'Địa điểm',
        vision: 'Tầm nhìn:',
        vision_description: 'Trở thành một trong những công ty sở hữu chuỗi cung ứng tốt nhất trong lĩnh vực Thiết bị Y tế theo tiêu chuẩn trên toàn cầu.',
        mission: 'Sứ mệnh:',
        mission_description:'Công ty Tập Đoàn Habimec được hình thành với mong muốn mang đến cộng đồng những trang thiết bị Y tế tốt nhất thế giới. Ngày càng nhiều người có cơ hội được sử dụng sản phẩm chất lượng với mức chi phí hợp lý.',
        core_value: 'Giá trị cốt lõi:',
        core_value_description: 'Lấy lợi ích sức khỏe của cộng đồng làm yếu tố hàng đầu, là kim chỉ nam cho mọi hoạt động kinh doanh của công ty.',
        product_description: 'Cùng bảo vệ sức khỏe cộng đồng và ngăn ngừa sự lây lan của bệnh Covid-19, chúng tôi xin giới thiệu các sản phẩm chủ yếu bao gồm: Khẩu trang, quần áo chống dịch & găng tay và các thiết bị bảo vệ khác có thể giúp ngăn chặn sự lây lan của coronavirus.',
        'latex_medical_gloves': 'Nhà máy sản xuất găng tay y tế',
        address: 'KCN Lai Uyên, Lai Uyên, Bàu Bàng, Bình Dương',
        "Estimated total investment": "Tổng mức đầu tư dự kiến",
        "Total factory area": "Tổng diện tích nhà máy",
        "Number of production lines": "Số lượng dây chuyền sản xuất",
        "Capacity": "Công suất (22/24h)",
        "gloves  per line": "chiếc/ dây chuyền",
        "lines": "dây chuyền",
        "(hight 16m - 19m)": "(chiều cao 16m– 19m)",
        "Habimec provides": "Habimec cung cấp đầy đủ tất cả các chứng chỉ Việt Nam và quốc tế như: FDA, CE, ISO,….",
        "our certificate": "Chứng chỉ của chúng tôi",
        "Representative office": "VĂN PHÒNG ĐẠI ĐIỆN",
        "Factory No. 1": "NHÀ MÁY SỐ 1",
        "Factory No. 2": "NHÀ MÁY SỐ 2",
        "address_office": "51 Nguyen Cư Trinh, Phường Nguyễn Cư Trinh, Quận 1, TP. Hồ Chí Minh, Việt Nam",
        "Factory No. 1 address": "KCN Quang Minh 1, Xã Quang Minh, Huyện Mê Linh, Thành phố Hà Nôi, Việt Nam",
        "Factory No. 2 address": "KCN Lai Uyên, Thị Trấn Lai Uyên, xã Long Nguyên, huyện Bàu Bàng, tỉnh Bình Dương, Việt Nam",
        "image-banner-about-us": ""

    },
    en: {
        home: 'Home',
        aboutUs: 'About us',
        product: 'Product',
        contact: 'Contact',
        certificate: 'CERTIFICATE',
        CONTACT_US: 'CONTACT US',
        HABIMECT_NAME: 'HABIMEC GROUP JOINT STOCK COMPANY',
        More: 'More',
        MESSAGE: 'MESSAGE',
        MESSAGE_DESCRIPTION_1: 'We are a leading manufacturer in medical equipment with extensive experience in manufacturing and exporting to Europe and America. The outbreak of Corona virus has caused a serious global health crisis, being able to protect public health and prevent the spread of Covid-19 is one of our main goals and we would like to introduce some of our main products that include: Face masks, anti-epidemic clothing, gloves and other protective equipment that can help to prevent the spread of Corona virus.',
        MESSAGE_DESCRIPTION_2: 'As a Vietnamese brand, we own and operate a factory system operating in accordance with ISO 9001: 2015 and ISO 13485: 2016 standards.',
        MESSAGE_DESCRIPTION_3: 'Our medical products are committed to quality and design to FDA and CE standards',
        MESSAGE_DESCRIPTION_4: 'HABIMEC GROUP constantly researches, sources and develops the best medical products helping to improve the efficiency of community healthcare.',
        nitrile_title: 'NITRILE MEDICAL GLOVES',
        nitrile_description: 'Made from Nitrile synthetic rubber. Nitrile gloves are great for those who are allergic to natural rubber....',
        latex_title: 'LATEX MEDICAL GLOVES',
        latex_description: 'Găng tay latex là loại găng tay được chiết xuất 100% từ cao su tự nhiên....',
        event: 'Event',
        content: 'Content',
        location: 'Location',
        vision: 'Vision:',
        vision_description: 'To become the company that owns the best supply chain in the field of Medical Equipment  according to global standards',
        mission: 'Mission:',
        mission_description:'Habimec Group Company was formed with the desire to bring to the community the best medical equipment in the world. More and more people have the opportunity to use quality products at a reasonable cost.',
        core_value: 'Core value:',
        core_value_description: 'Taking the health benefits of the community as the number one factor. That is the guideline for all business activities within the company.',
        product_description: 'The outbreak of Corona virus has caused a serious global health crisis, being able to protect public health and prevent the spread of Covid-19 is one of our main goals and we would like to introduce some of our main products that include: Face masks, anti-epidemic clothing, gloves and other protective equipment that can help to prevent the spread of Corona virus.',
        specifications: 'specifications',
        'latex_medical_gloves': 'Latex Medical Gloves',
        address: 'Lai Uyen Industrial Park, Lai Uyen, Bau Bang, Binh Duong',
        "Estimated total investment": "Estimated total investment",
        "Total factory area": "Total factory area",
        "Number of production lines": "Number of production lines",
        "Capacity": "Capacity (22/24h)",
        "gloves  per line": "gloves  per line",
        "lines": "lines",
        "(hight 16m - 19m)": "(hight 16m - 19m)",
        "Habimec provides": "Habimec provides all Vietnamese and international certificates such as: FDA, CE, ISO,….",
        "certificate": "Certificate",
        "Representative office": "Representative office",
        "Factory No. 1": "Factory No. 1",
        "Factory No. 2": "Factory No. 2",
        "address_office": "51 Nguyen Cu Trinh, Nguyen Cu Trinh Ward, District 1,  Ho Chi Minh City, Vietnam",
        "Factory No. 1 address": "Quang Minh Industrial Park 1, Quang Minh Commune, Me Linh District, Ha Noi Capital, Vietnam",
        "Factory No. 2 address": "Lai Uyen Industrial Park, Lai Uyen Town, Long Nguyen Commune, Bau Bang District, Binh Duong Province, Vietnam",
        "our certificate": "Our certificates",
    }
}

export const pathProductDetails = [
    { key: 'sp-1', name: 'GĂNG TAY Y TẾ NITRILE', id: 'nitrile-medical-gloves', content: 'nitrile_description', title: 'nitrile_title', image: '/images/original/product/Banner 1-08.png' },
    { key: 'sp-2', name: 'GĂNG TAY Y TẾ LATEX GLOVES', id: 'latex-medical-gloves', content: 'latex_description', title: 'latex_title', image: '/images/original/product/Banner 1-10.png' },
]